config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users do
    member do
      get '/all', to: 'prattles#all', as: :prattles_for
    end
  end

  resources :prattles

  resource :session, only: [:new, :create, :destroy]
end

app/models/prattle.rb
# == Schema Information
#
# Table name: prattles
#
#  id         :integer          not null, primary key
#  content    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Prattle < ActiveRecord::Base
  belongs_to :user

  validates :content, length: { maximum: 80 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :prattles

  validates :username, presence: true
  validates :email, presence: true

  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def login!(user)
    session[:current_user_id] = user.id
  end

  def logout!
    session[:current_user_id] = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def require_current_user
    unless current_user
      flash[:message] = "You must be signed in to do that!"
      redirect_to new_session_path
    end
  end
end

app/controllers/prattles_controller.rb
class PrattlesController < ApplicationController
  before_action :require_current_user, only: :create

  def create
    @prattle = current_user.prattles.new(prattle_params)

    if @prattle.save
      redirect_to current_user
    else
      flash[:message] = @prattle.errors.full_messages.to_sentence
      redirect_to current_user
    end
  end

  private
  def prattle_params
    params.require(:prattle).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: user_params[:username])

    if @user.authenticate(user_params[:password])
      login!(@user)
      redirect_to user_path(@user.id)
    else
      flash[:message] = "Username or Password error, kiddo."
    end
  end

  def destroy
    logout!
    redirect_to new_session_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user, only: :show

  def show
    respond_to do |format|
      format.html
      # instead of this: look up JSON Builder
      format.json { render json: @user.to_json(include: :prattles) }
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to @user
      # redirect_to user_path(@user.id)
    else
      flash[:message] = @user.errors
                             .full_messages
                             .to_sentence

      redirect_to new_user_path
    end
  end

  private

  def fetch_user
    @user = User.includes(:prattles).find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prattles_helper.rb
module PrattlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toddlr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <form action="<%= prattles_path %>" method="post">
    <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
    <input type="text"
           name="prattle[content]"
           placeholder="prattle on" autofocus="true">
  </form>

  <%= button_to "Log out", session_path, method: :delete %>
<% end %>

<% if flash[:message] %>
  <div class="message">
    <%= flash[:message] %>
  </div>
<% end %>


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="<%= users_path %>" method="post">
  <h1>Sign up to Todd.lr</h1>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <input type="text"
         name="user[username]"
         placeholder="user name">
  <input type="email"
         name="user[email]"
         placeholder="email">
  <input type="password"
         name="user[password]"
         placeholder="password">
  <input type="password"
         name="user[password_confirmation]"
         placeholder="confirm your password">
  <input type="submit" value="Do it!">
  <div class="text-center">- or -</div>
  <a class="button" href="<%= new_session_path %>">Sign in, instead!</a>
</form>

app/views/users/show.html.erb
<h1>Prattles for <%= @user.username %></h1>

<% @user.prattles.each do |prattle| %>
  <h3><%= prattle.content %></h3>
<% end %>